### ISSUE TITLE
Tag support

### ISSUE THREAD

**Issue by denisidoro** [go-graphite/docker-go-graphite#18]
Is there any way to make [tags](https://graphite.readthedocs.io/en/stable/tags.html) work as expected?

I ingested data into graphite using the pickle format and here's what I get:

<img width="710" alt="Screen Shot 2021-02-02 at 07 41 01" src="https://user-images.githubusercontent.com/3226564/106589595-f0ec9380-652a-11eb-8cf3-728bf230c551.png">

You can see that the metric names preserved `;...`, which I think they shouldn't. 

Clicking on `seriesByTag` in the screenshot above does nothing (the function dropdown gets deselected) and sometimes grafana displays a red rectangle with `404 not found`

I even tried [upgrading all dependencies](https://github.com/go-graphite/docker-go-graphite/pull/17). Same error.

Sidenote: I tried tweaking with the datasource settings inside Grafana. Still no luck.

**Comment by denisidoro** [comment]
<img width="927" alt="Screen Shot 2021-02-02 at 08 01 08" src="https://user-images.githubusercontent.com/3226564/106591344-eb904880-652c-11eb-9089-e4a4ea8530e9.png">

**Comment by denisidoro** [comment]
However, this works:

<img width="704" alt="Screen Shot 2021-02-02 at 08 03 38" src="https://user-images.githubusercontent.com/3226564/106591897-96086b80-652d-11eb-98f2-989e53bd0ace.png">

**Comment by denisidoro** [comment]
Maybe related: https://community.grafana.com/t/seriesbytag-not-returning-any-data/16460

**Comment by Civil** [comment]
go-carbon that is used in this image do not have Tag support at all.

If you want to have working tags, you have 2 options:

**Option 1. Use clickhouse-based stack.**

  You need to replace go-carbon with github.com/lomik/graphite-clickhouse (query part of pipeline), github.com/lomik/carbon-clickhouse (ingestion part of pipeline) and github.com/clickhouse/clickhouse (database).

  https://github.com/lomik/graphite-clickhouse-tldr - also have some instructions on how to set it up. There is a docker-compose files there, but they use rather outdated versions of all components and they have graphite-web instead of grafana+carbonapi.


**Option 2. Use VictoriaMetrics as backend.**

In that case just replace go-carbon with github.com/VictoriaMetrics/VictoriaMetrics/ and change config file of carbonapi to use VictoriaMetrics specific protocol

  VictoriaMetrics should be easier to maintain, but it is less tested (to my knowledge author of graphite-clickhouse uses carbonapi at his workplace, and there are other people who use Clickhouse stack, but I'm not aware about any VictoriaMetrics+carbonapi combination in production anywhere).


There is an Option 3 but I doubt you'll like it. There were some efforts in implementing tag support in go-carbon: https://github.com/Civil/go-carbon-old - but it's unfinished and only /find requests worked. You can help finishing it and updating underlying go-carbon to current master, as last time I've touched it, was in 2019.

**Comment by deniszh** [comment]
Indeed, I had idea to create same image for VictoriaMetrics+carbonapi, which I tested and got quite impressive results, but not on prod - https://github.com/deniszh/graphite-victoriametrics-tldr

**Comment by deniszh** [comment]
Correction: I didn’t test tags in vm + carbonapi, only normal metrics.

**Comment by Civil** [comment]
Tags should also work rather fast, especially when most recent version of VM is combined with recent carbonapi (VM have some new APIs that carbonapi can now use).

**Comment by denisidoro** [comment]
I ended up using the official [VictoriaMetrics docker-compose file](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose.yml) with:
- Influx syntax for data ingestion
- MetricsQL for querying

This solution meets my needs.

Thanks for the suggestions! 👍
